---
apiVersion: v1
kind: Pod
metadata:
  name: web-server
  labels:
    environment: production
    app: nginx
spec:
  containers:
  - name: web-server
    image: nginx
    ports:
    - containerPort: 80
